apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-ops-view
  namespace: monitor

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-ops-view
  namespace: monitor
rules:
- apiGroups: [""]
  resources: ["nodes", "pods"]
  verbs:
    - list
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs:
    - get
    - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-ops-view
  namespace: monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-ops-view
subjects:
- kind: ServiceAccount
  name: kube-ops-view
  namespace: monitor

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ops-view
  namespace: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ops-view
  template:
    metadata:
      labels:
        app: ops-view
    spec:
      serviceAccountName: kube-ops-view
      containers:
        - name: ops-view
          image: hjacobs/kube-ops-view
          ports:
            - containerPort: 8080
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: ops-view-svc
  namespace: monitor
spec:
  type: NodePort
  selector:
    app: ops-view
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30092