apiVersion: v1
kind: Service
metadata:
  name: canary-svc
  namespace: udacity
spec:
  type: ClusterIP
  selector:
    app: canary
    version: "1.0"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80